enable_back_ups: 'true'
time_between_back_ups_in_hours: '24'
regeneration:
   enable: 'true'
   burn:
      enable: 'true'
      delay: 10
gridsize: 32
plot_size: 15
wars:
   battles:
      deathmatch:
         use_multiplier: 'false'
         kills_for_win_multiplier: '5'
         kills_for_win: 30
      obliteration:
         use_multipliers: 'false'
         kills_for_win_multiplier: 5
         damage_for_win_multiplier: 5
         kill_for_win: 30
         damage_for_win: 100