enable_back_ups: 'true'
time_between_back_ups_in_hours: '24'
regeneration:
   enable: 'true'
   burn:
      enable: 'true'
      delay: 10
gridsize: 32
plot_size: 15
wars:
   battles:
      deathmatch:
         use_multiplier: 'false'
         kills_for_win_multiplier: 5
         kills_for_win: 2
      obliteration:
         use_multipliers: 'false'
         kills_for_win_multiplier: 5
         damage_for_win_multiplier: 5
         kills_for_win: 2
         damage_for_win: 100
      #Length of battle in minutes
      length: 10.0
      #Period after the battle in which the loosing empire cannot be attacked / mins
      saftey_period: 60.0
      
      percentage_gain_per_win: 10.0
   #Time after breaking an alliance before the empire breaking the alliance can attack / mins
   ex_ally_timer: 240.0
   #The time which 2 empies have to wait after finishing one war before starting another / mins
   ex_enemy_timer: 2880.0